.TH KBBIND 1 2010-12-25 "" "User Commands"

.SH NAME
kbbind \- Remap keys and run commands

.SH SYNOPSIS
.B kbbind
[\fB\-sdv\fR] [\fB\-p \fR\fIfile\fR] [\fB\-u \fR\fIpath\fR] [\fB\-n \fR\fIname\fR] \fB\-e\fR|<\fIconfig file\fR> <\fIinput device\fR>

.SH DESCRIPTION
Utility for mapping keys/combinations to other keys/combinations/commands. Events are read from a single keyboard via an event device and any mapped keys are passed back to the kernel through a virtual input (uinput) device.

.SH OPTIONS
.TP
\fB\-s\fR
Sink mode - Trap all events and only forward mapped ones
.TP
\fB\-d\fR
Detach from console and run as a daemon, send messages to syslog
.TP
\fB\-v\fR
Print version number and exit
.TP
\fB\-p \fR\fIfile\fR
Write PID to file and delete on exit
.TP
\fB\-u \fR\fIpath\fR
Override default uinput device path (\fI/dev/input/uinput\fR)
.TP
\fB\-n \fR\fIname\fR
Override default uinput device name (kbbind virtual keyboard)
.TP
\fB\-e\fR
Read events from device and print key events to stdout.

.SH CONFIGURATION
The configuration file allows one directive per line with arguments seperated by spaces/tabs, lines starting with a hash (#) character are ignored. Single keys or combinations using the \fIx\fR+\fIy\fR+\fIz\fR syntax may be used with all directives. The following directives may be used:
.TP
\fBmap \fR<\fIkey a\fR> <\fIkey b\fR>
Map key \fIa\fR to \fIb\fR. For example 'map 75 125+103' maps key 75 to combination 125+103.
.TP
\fBdrop \fR<\fIkey\fR>
Drop events recieved for the given key. If a combination is supplied, the individual keys will not be ignored, only the inputs from the last key in the combination while the rest are held down. Using this while sink mode (-s) is in use is redundant as all unmapped keys will be ignored by default.
.TP
\fBexec \fR<\fIkey\fR> <\fIcommand\fR>
Execute a shell command when the given key is pressed or autorepeats. The terminal will be redirected to \fI/dev/null\fR when kbbind is running as a daemon.
.TP
\fBalias \fR<\fIname\fR> <\fIkey\fR>
Set an alias to the specified key, any existing alias will be replaced. The alias may refer to a combination and may be used anywhere, for example, the following \fBmap\fR statements are effectively the same:
.PP
.RS
.RS
alias win 125
.br
alias win_up win+103
.PP
map 75 125+103
.br
map 75 win+103
.br
map 75 win_up
.RE
.RE

.SH ENVIRONMENT
.TP
\fBSHELL\fR
Set the shell used to execute commands, \fI/bin/sh\fR will be used if this is not set.

.SH AUTHOR
Daniel Collins <solemnwarning@solemnwarning.net>
